"""extend classification rules for fact and line-scoped outcomes

Adds the columns a fact-dependent rule needs (both outcome branches), the
"undue cost or effort" landing category for IFRS 18 B65 and B72, the
line-scoped fact key, and the flags for forced review and the residual rule.

The CHECK constraints below are written by hand: Alembic autogenerate does
not diff CheckConstraints, so only the columns were detected. See
`tests/test_enum_constraints.py`, which compares every generated enum
constraint against the live database.

Revision ID: f4a67c7f8074
Revises: c23f659641c8
Create Date: 2026-09-19 01:57:53.273329+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f4a67c7f8074"
down_revision: str | None = "c23f659641c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classification_rules",
        sa.Column("fact_true_category", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "classification_rules",
        sa.Column("fact_true_subcategory", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "classification_rules",
        sa.Column("undue_cost_category", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "classification_rules",
        sa.Column("requires_line_fact", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "classification_rules", sa.Column("requires_human_review", sa.Boolean(), nullable=False)
    )
    op.add_column("classification_rules", sa.Column("is_residual", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

    # Hand-written: autogenerate does not diff CheckConstraints.
    #
    # Column names are kept short on purpose. PostgreSQL truncates identifiers
    # at 63 characters, and the naming convention prefixes each constraint with
    # "ck_<table>_". `outcome_when_fact_true_subcategory` produced a 64-character
    # constraint name, which PostgreSQL silently truncated — leaving a
    # constraint the application could not find by name.
    # `tests/test_identifier_lengths.py` now fails on any such name.
    op.create_check_constraint(
        "fact_true_category_valid",
        "classification_rules",
        "fact_true_category IS NULL OR fact_true_category IN "
        "('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', "
        "'UNCLASSIFIED')",
    )
    op.create_check_constraint(
        "fact_true_subcategory_valid",
        "classification_rules",
        "fact_true_subcategory IS NULL OR fact_true_subcategory IN "
        "('DISCONTINUED_RESULT', 'FINANCING_EXPENSE', 'FINANCING_INCOME', "
        "'INCOME_TAX_EXPENSE', 'INCOME_TAX_INCOME', 'INVESTING_EXPENSE', 'INVESTING_INCOME', "
        "'OPERATING_EXPENSE', 'OPERATING_OTHER', 'OPERATING_REVENUE')",
    )
    op.create_check_constraint(
        "undue_cost_category_valid",
        "classification_rules",
        "undue_cost_category IS NULL OR undue_cost_category IN "
        "('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', "
        "'UNCLASSIFIED')",
    )
    op.drop_constraint("rule_must_assign_or_inherit", "classification_rules", type_="check")
    op.create_check_constraint(
        "rule_must_assign_or_inherit",
        "classification_rules",
        "outcome_category IS NOT NULL OR inherits_category OR fact_true_category IS NOT NULL",
    )
    op.create_check_constraint(
        "fact_rule_defines_both_outcomes",
        "classification_rules",
        "requires_activity_fact IS NULL OR (fact_true_category IS NOT NULL "
        "AND outcome_category IS NOT NULL)",
    )
    op.create_check_constraint(
        "line_fact_needs_undue_cost",
        "classification_rules",
        "requires_line_fact IS NULL OR undue_cost_category IS NOT NULL",
    )


def downgrade() -> None:
    for name in (
        "line_fact_needs_undue_cost",
        "fact_rule_defines_both_outcomes",
        "undue_cost_category_valid",
        "fact_true_subcategory_valid",
        "fact_true_category_valid",
    ):
        op.drop_constraint(name, "classification_rules", type_="check")
    op.drop_constraint("rule_must_assign_or_inherit", "classification_rules", type_="check")
    op.create_check_constraint(
        "rule_must_assign_or_inherit",
        "classification_rules",
        "outcome_category IS NOT NULL OR inherits_category",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classification_rules", "is_residual")
    op.drop_column("classification_rules", "requires_human_review")
    op.drop_column("classification_rules", "requires_line_fact")
    op.drop_column("classification_rules", "undue_cost_category")
    op.drop_column("classification_rules", "fact_true_subcategory")
    op.drop_column("classification_rules", "fact_true_category")
    # ### end Alembic commands ###
