"""initial schema

Revision ID: 1558c0538102
Revises:
Create Date: 2026-09-19 01:16:09.315622+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1558c0538102"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `users.email` uses CITEXT so address comparison is case-insensitive.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_rules",
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outcome_category", sa.String(length=64), nullable=True),
        sa.Column("outcome_subcategory", sa.String(length=64), nullable=True),
        sa.Column("inherits_category", sa.Boolean(), nullable=False),
        sa.Column("requires_activity_fact", sa.String(length=64), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("verification_status", sa.String(length=64), nullable=False),
        sa.Column("verification_note", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("confidence_ceiling", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome_category IS NULL OR outcome_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_classification_rules_outcome_category_valid"),
        ),
        sa.CheckConstraint(
            "outcome_subcategory IS NULL OR outcome_subcategory IN ('DISCONTINUED_RESULT', 'FINANCING_EXPENSE', 'FINANCING_INCOME', 'INCOME_TAX_EXPENSE', 'INCOME_TAX_INCOME', 'INVESTING_EXPENSE', 'INVESTING_INCOME', 'OPERATING_EXPENSE', 'OPERATING_OTHER', 'OPERATING_REVENUE')",
            name=op.f("ck_classification_rules_outcome_subcategory_valid"),
        ),
        sa.CheckConstraint(
            "requires_activity_fact IS NULL OR requires_activity_fact IN ('FINANCIAL_SERVICES', 'INVESTING_IN_ASSETS', 'INVESTMENT', 'LENDING', 'OTHER', 'PROVIDING_FINANCING_TO_CUSTOMERS', 'REAL_ESTATE')",
            name=op.f("ck_classification_rules_requires_activity_fact_valid"),
        ),
        sa.CheckConstraint(
            "source_type IN ('BIG4', 'IASB_EDUCATIONAL', 'IFRS_STANDARD', 'OTHER', 'TAXONOMY')",
            name=op.f("ck_classification_rules_source_type_valid"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('UNVERIFIED', 'VERIFIED_PRIMARY', 'VERIFIED_SECONDARY')",
            name=op.f("ck_classification_rules_verification_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence_ceiling IS NULL OR (confidence_ceiling > 0 AND confidence_ceiling <= 1)",
            name=op.f("ck_classification_rules_confidence_ceiling_in_range"),
        ),
        sa.CheckConstraint(
            "outcome_category IS NOT NULL OR inherits_category",
            name=op.f("ck_classification_rules_rule_must_assign_or_inherit"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["classification_rules.id"],
            name=op.f("fk_classification_rules_superseded_by_classification_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_rules")),
        sa.UniqueConstraint("rule_id", "version", name=op.f("uq_classification_rules_rule_id")),
    )
    op.create_index(
        op.f("ix_classification_rules_priority"), "classification_rules", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_classification_rules_rule_id"), "classification_rules", ["rule_id"], unique=False
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("identifier", sa.String(length=100), nullable=True),
        sa.Column("identifier_scheme", sa.String(length=64), nullable=True),
        sa.Column("jurisdiction", sa.String(length=2), nullable=False),
        sa.Column("industry_code", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "identifier_scheme IS NULL OR identifier_scheme IN ('DART', 'KR_BRN', 'LEI')",
            name=op.f("ck_companies_identifier_scheme_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_table(
        "normalized_accounts",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("label_ko", sa.String(length=300), nullable=False),
        sa.Column("label_en", sa.String(length=300), nullable=False),
        sa.Column("statement_section", sa.String(length=64), nullable=False),
        sa.Column("default_nature", sa.String(length=64), nullable=True),
        sa.Column("parent_code", sa.String(length=100), nullable=True),
        sa.Column("ambiguous_by_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_nature IS NULL OR default_nature IN ('EXPENSE', 'INCOME')",
            name=op.f("ck_normalized_accounts_default_nature_valid"),
        ),
        sa.CheckConstraint(
            "statement_section IN ('BS', 'OCI', 'PL')",
            name=op.f("ck_normalized_accounts_statement_section_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_code"],
            ["normalized_accounts.code"],
            name=op.f("fk_normalized_accounts_parent_code_normalized_accounts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_accounts")),
        sa.UniqueConstraint("code", name=op.f("uq_normalized_accounts_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'PREPARER', 'REVIEWER', 'VIEWER')", name=op.f("ck_users_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "account_synonyms",
        sa.Column("normalized_account_id", sa.UUID(), nullable=False),
        sa.Column("synonym", sa.String(length=300), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("match_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("locale IN ('ko', 'en')", name=op.f("ck_account_synonyms_locale_valid")),
        sa.CheckConstraint(
            "match_type IN ('EXACT', 'NORMALIZED', 'REGEX')",
            name=op.f("ck_account_synonyms_match_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_account_id"],
            ["normalized_accounts.id"],
            name=op.f("fk_account_synonyms_normalized_account_id_normalized_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_synonyms")),
        sa.UniqueConstraint("synonym", "locale", name=op.f("uq_account_synonyms_synonym")),
    )
    op.create_index(
        op.f("ix_account_synonyms_synonym"), "account_synonyms", ["synonym"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("basis", sa.String(length=64), nullable=False),
        sa.Column("presentation_currency", sa.String(length=3), nullable=False),
        sa.Column("presentation_scale", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("reconciliation_status", sa.String(length=64), nullable=False),
        sa.Column("rule_set_version", sa.String(length=50), nullable=True),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis IN ('CONSOLIDATED', 'SEPARATE')", name=op.f("ck_projects_basis_valid")
        ),
        sa.CheckConstraint(
            "reconciliation_status IN ('FAILED', 'NOT_RUN', 'PASSED')",
            name=op.f("ck_projects_reconciliation_status_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'FINALIZED' OR finalized_at IS NOT NULL",
            name=op.f("ck_projects_finalized_requires_timestamp"),
        ),
        sa.CheckConstraint(
            "status <> 'FINALIZED' OR reconciliation_status = 'PASSED'",
            name=op.f("ck_projects_finalized_requires_reconciliation"),
        ),
        sa.CheckConstraint(
            "status IN ('CLASSIFIED', 'DRAFT', 'EXTRACTED', 'EXTRACTION_FAILED', 'FINALIZED', 'IN_REVIEW', 'RECONCILIATION_FAILED', 'UPLOADED')",
            name=op.f("ck_projects_status_valid"),
        ),
        sa.CheckConstraint("period_end >= period_start", name=op.f("ck_projects_period_ordered")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_projects_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_projects_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "action IN ('ACCEPTED', 'CLASSIFIED', 'CREATED', 'DECOMPOSED', 'DELETED', 'EXPORTED', 'EXTRACTED', 'FINALIZED', 'OVERRIDDEN', 'QUESTION_ANSWERED', 'UPDATED')",
            name=op.f("ck_audit_logs_action_valid"),
        ),
        sa.CheckConstraint(
            "actor_type IN ('AI', 'SYSTEM', 'USER')", name=op.f("ck_audit_logs_actor_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_logs_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_entity", "audit_logs", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "ix_audit_project_time", "audit_logs", ["project_id", "occurred_at"], unique=False
    )
    op.create_table(
        "business_activities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("activity_type", sa.String(length=64), nullable=False),
        sa.Column("is_main_business_activity", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (confirmed_by_user AND source = 'AI_SUGGESTED')",
            name=op.f("ck_business_activities_ai_cannot_self_confirm"),
        ),
        sa.CheckConstraint(
            "activity_type IN ('FINANCIAL_SERVICES', 'INVESTING_IN_ASSETS', 'INVESTMENT', 'LENDING', 'OTHER', 'PROVIDING_FINANCING_TO_CUSTOMERS', 'REAL_ESTATE')",
            name=op.f("ck_business_activities_activity_type_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('AI_SUGGESTED', 'DOCUMENT', 'USER')",
            name=op.f("ck_business_activities_source_valid"),
        ),
        sa.CheckConstraint(
            "NOT confirmed_by_user OR confirmed_at IS NOT NULL",
            name=op.f("ck_business_activities_confirmed_requires_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_business_activities_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["users.id"], name=op.f("fk_business_activities_confirmed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_business_activities_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_activities")),
        sa.UniqueConstraint(
            "company_id",
            "project_id",
            "activity_type",
            name=op.f("uq_business_activities_company_id"),
        ),
    )
    op.create_table(
        "impact_analyses",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_set_version", sa.String(length=50), nullable=True),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reconciliation_status", sa.String(length=64), nullable=False),
        sa.Column("reconciliation_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("kpis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("waterfall", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reconciliation_status IN ('FAILED', 'NOT_RUN', 'PASSED')",
            name=op.f("ck_impact_analyses_reconciliation_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_impact_analyses_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impact_analyses")),
    )
    op.create_index(
        "ix_impact_current", "impact_analyses", ["project_id", "is_current"], unique=False
    )
    op.create_table(
        "uploaded_files",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("scan_status", sa.String(length=64), nullable=False),
        sa.Column("parse_status", sa.String(length=64), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parse_status IN ('FAILED', 'PARSED', 'PENDING')",
            name=op.f("ck_uploaded_files_parse_status_valid"),
        ),
        sa.CheckConstraint(
            "scan_status IN ('CLEAN', 'INFECTED', 'PENDING', 'SKIPPED')",
            name=op.f("ck_uploaded_files_scan_status_valid"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_uploaded_files_size_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_uploaded_files_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_uploaded_files_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_files")),
    )
    op.create_index(op.f("ix_uploaded_files_sha256"), "uploaded_files", ["sha256"], unique=False)
    op.create_table(
        "exports",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("impact_analysis_id", sa.UUID(), nullable=True),
        sa.Column("format", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("is_watermarked_unreconciled", sa.Boolean(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("format IN ('PDF', 'XLSX')", name=op.f("ck_exports_format_valid")),
        sa.CheckConstraint(
            "status IN ('FAILED', 'PENDING', 'READY')", name=op.f("ck_exports_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["impact_analysis_id"],
            ["impact_analyses.id"],
            name=op.f("fk_exports_impact_analysis_id_impact_analyses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_exports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_exports_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    op.create_table(
        "financial_statements",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_file_id", sa.UUID(), nullable=True),
        sa.Column("statement_type", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("is_comparative", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("scale", sa.Integer(), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statement_type IN ('BALANCE_SHEET', 'CASH_FLOW', 'CHANGES_IN_EQUITY', 'INCOME_STATEMENT', 'OTHER_COMPREHENSIVE_INCOME')",
            name=op.f("ck_financial_statements_statement_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_financial_statements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_file_id"],
            ["uploaded_files.id"],
            name=op.f("fk_financial_statements_uploaded_file_id_uploaded_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statements")),
    )
    op.create_table(
        "financial_statement_lines",
        sa.Column("statement_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("raw_label", sa.String(length=500), nullable=False),
        sa.Column("raw_value", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=6), nullable=False),
        sa.Column("sign_normalization", sa.String(length=64), nullable=False),
        sa.Column("is_subtotal", sa.Boolean(), nullable=False),
        sa.Column("subtotal_kind", sa.String(length=64), nullable=True),
        sa.Column("parent_line_id", sa.UUID(), nullable=True),
        sa.Column("decomposition_status", sa.String(length=64), nullable=False),
        sa.Column("normalized_account_id", sa.UUID(), nullable=True),
        sa.Column("normalization_method", sa.String(length=64), nullable=True),
        sa.Column("normalization_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("current_category", sa.String(length=100), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note_references", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_subtotal OR decomposition_status = 'NOT_REQUIRED'",
            name=op.f("ck_financial_statement_lines_subtotal_not_decomposable"),
        ),
        sa.CheckConstraint(
            "decomposition_status <> 'DECOMPOSED' OR parent_line_id IS NULL",
            name=op.f("ck_financial_statement_lines_decomposed_parent_is_not_a_child"),
        ),
        sa.CheckConstraint(
            "decomposition_status IN ('ACCEPTED_AGGREGATE', 'DECOMPOSED', 'NOT_REQUIRED', 'REQUIRED')",
            name=op.f("ck_financial_statement_lines_decomposition_status_valid"),
        ),
        sa.CheckConstraint(
            "normalization_method IS NULL OR normalization_method IN ('AI', 'EXACT', 'FUZZY', 'MANUAL', 'SYNONYM')",
            name=op.f("ck_financial_statement_lines_normalization_method_valid"),
        ),
        sa.CheckConstraint(
            "sign_normalization IN ('AS_IS', 'EXPENSE_COLUMN_NEGATED', 'NEGATED', 'PARENTHESES_NEGATED')",
            name=op.f("ck_financial_statement_lines_sign_normalization_valid"),
        ),
        sa.CheckConstraint(
            "subtotal_kind IS NULL OR subtotal_kind IN ('GROSS_PROFIT', 'OTHER', 'PROFIT_BEFORE_TAX', 'PROFIT_FOR_THE_PERIOD', 'REPORTED_OPERATING_PROFIT')",
            name=op.f("ck_financial_statement_lines_subtotal_kind_valid"),
        ),
        sa.CheckConstraint(
            "NOT is_subtotal OR normalized_account_id IS NULL",
            name=op.f("ck_financial_statement_lines_subtotal_has_no_account"),
        ),
        sa.CheckConstraint(
            "depth >= 0", name=op.f("ck_financial_statement_lines_depth_non_negative")
        ),
        sa.CheckConstraint(
            "is_subtotal OR subtotal_kind IS NULL",
            name=op.f("ck_financial_statement_lines_subtotal_kind_requires_subtotal"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0", name=op.f("ck_financial_statement_lines_ordinal_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["normalized_account_id"],
            ["normalized_accounts.id"],
            name=op.f("fk_financial_statement_lines_normalized_account_id_normalized_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_line_id"],
            ["financial_statement_lines.id"],
            name=op.f("fk_financial_statement_lines_parent_line_id_financial_statement_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["financial_statements.id"],
            name=op.f("fk_financial_statement_lines_statement_id_financial_statements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statement_lines")),
        sa.UniqueConstraint(
            "statement_id", "ordinal", name=op.f("uq_financial_statement_lines_statement_id")
        ),
    )
    op.create_index(
        "ix_fsl_statement_summable",
        "financial_statement_lines",
        ["statement_id", "is_subtotal", "decomposition_status"],
        unique=False,
    )
    op.create_table(
        "review_questions",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=True),
        sa.Column("question_key", sa.String(length=100), nullable=False),
        sa.Column("question_text_ko", sa.Text(), nullable=False),
        sa.Column("question_text_en", sa.Text(), nullable=False),
        sa.Column("raised_by_rule_id", sa.String(length=100), nullable=True),
        sa.Column("answer", sa.String(length=64), nullable=True),
        sa.Column("resolved_category", sa.String(length=64), nullable=True),
        sa.Column("undue_cost_or_effort", sa.Boolean(), nullable=False),
        sa.Column("answered_by", sa.UUID(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("resulting_activity_id", sa.UUID(), nullable=True),
        sa.Column("blocks_finalization", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'LINE') = (line_id IS NOT NULL)",
            name=op.f("ck_review_questions_line_scope_requires_line"),
        ),
        sa.CheckConstraint(
            "answer IS NULL OR answer IN ('NO', 'NOT_SURE', 'YES')",
            name=op.f("ck_review_questions_answer_valid"),
        ),
        sa.CheckConstraint(
            "resolved_category IS NULL OR resolved_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_review_questions_resolved_category_valid"),
        ),
        sa.CheckConstraint(
            "scope IN ('COMPANY', 'LINE')", name=op.f("ck_review_questions_scope_valid")
        ),
        sa.CheckConstraint(
            "answer IS NULL OR (answered_by IS NOT NULL AND answered_at IS NOT NULL)",
            name=op.f("ck_review_questions_answer_records_answerer"),
        ),
        sa.ForeignKeyConstraint(
            ["answered_by"], ["users.id"], name=op.f("fk_review_questions_answered_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["financial_statement_lines.id"],
            name=op.f("fk_review_questions_line_id_financial_statement_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_review_questions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resulting_activity_id"],
            ["business_activities.id"],
            name=op.f("fk_review_questions_resulting_activity_id_business_activities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_questions")),
        sa.UniqueConstraint(
            "project_id", "question_key", "line_id", name=op.f("uq_review_questions_project_id")
        ),
    )
    op.create_index(
        op.f("ix_review_questions_project_id"), "review_questions", ["project_id"], unique=False
    )
    op.create_table(
        "ifrs18_classifications",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("original_account", sa.String(length=500), nullable=False),
        sa.Column("normalized_account_code", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=38, scale=6), nullable=False),
        sa.Column("current_category", sa.String(length=100), nullable=True),
        sa.Column("proposed_ifrs18_category", sa.String(length=64), nullable=True),
        sa.Column("proposed_ifrs18_subcategory", sa.String(length=64), nullable=True),
        sa.Column("final_ifrs18_category", sa.String(length=64), nullable=True),
        sa.Column("final_ifrs18_subcategory", sa.String(length=64), nullable=True),
        sa.Column("classification_method", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=True),
        sa.Column("rule_set_version", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("ai_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("ai_raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence_band", sa.String(length=64), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("blocked_on_question_id", sa.UUID(), nullable=True),
        sa.Column("user_override", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=True),
        sa.Column("impact_on_operating_profit", sa.Numeric(precision=38, scale=6), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT user_override OR classification_method = 'USER'",
            name=op.f("ck_ifrs18_classifications_override_sets_user_method"),
        ),
        sa.CheckConstraint(
            "classification_method <> 'AI' OR requires_human_review",
            name=op.f("ck_ifrs18_classifications_ai_always_requires_review"),
        ),
        sa.CheckConstraint(
            "classification_method <> 'RULE' OR rule_id IS NOT NULL",
            name=op.f("ck_ifrs18_classifications_rule_method_records_rule_id"),
        ),
        sa.CheckConstraint(
            "classification_method IN ('AI', 'RESIDUAL_DEFAULT', 'RULE', 'UNRESOLVED', 'USER')",
            name=op.f("ck_ifrs18_classifications_classification_method_valid"),
        ),
        sa.CheckConstraint(
            "confidence_band IS NULL OR confidence_band IN ('HIGH', 'LOW', 'MEDIUM')",
            name=op.f("ck_ifrs18_classifications_confidence_band_valid"),
        ),
        sa.CheckConstraint(
            "final_ifrs18_category IS NULL OR final_ifrs18_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_ifrs18_classifications_final_ifrs18_category_valid"),
        ),
        sa.CheckConstraint(
            "final_ifrs18_subcategory IS NULL OR final_ifrs18_subcategory IN ('DISCONTINUED_RESULT', 'FINANCING_EXPENSE', 'FINANCING_INCOME', 'INCOME_TAX_EXPENSE', 'INCOME_TAX_INCOME', 'INVESTING_EXPENSE', 'INVESTING_INCOME', 'OPERATING_EXPENSE', 'OPERATING_OTHER', 'OPERATING_REVENUE')",
            name=op.f("ck_ifrs18_classifications_final_ifrs18_subcategory_valid"),
        ),
        sa.CheckConstraint(
            "proposed_ifrs18_category IS NULL OR proposed_ifrs18_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_ifrs18_classifications_proposed_ifrs18_category_valid"),
        ),
        sa.CheckConstraint(
            "proposed_ifrs18_subcategory IS NULL OR proposed_ifrs18_subcategory IN ('DISCONTINUED_RESULT', 'FINANCING_EXPENSE', 'FINANCING_INCOME', 'INCOME_TAX_EXPENSE', 'INCOME_TAX_INCOME', 'INVESTING_EXPENSE', 'INVESTING_INCOME', 'OPERATING_EXPENSE', 'OPERATING_OTHER', 'OPERATING_REVENUE')",
            name=op.f("ck_ifrs18_classifications_proposed_ifrs18_subcategory_valid"),
        ),
        sa.CheckConstraint(
            "NOT user_override OR (reviewer_user_id IS NOT NULL AND reviewed_at IS NOT NULL)",
            name=op.f("ck_ifrs18_classifications_override_records_reviewer"),
        ),
        sa.CheckConstraint(
            "ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)",
            name=op.f("ck_ifrs18_classifications_ai_confidence_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["blocked_on_question_id"],
            ["review_questions.id"],
            name=op.f("fk_ifrs18_classifications_blocked_on_question_id_review_questions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["financial_statement_lines.id"],
            name=op.f("fk_ifrs18_classifications_line_id_financial_statement_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_ifrs18_classifications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_ifrs18_classifications_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ifrs18_classifications")),
        sa.UniqueConstraint("line_id", name=op.f("uq_ifrs18_classifications_line_id")),
    )
    op.create_index(
        "ix_classification_review_queue",
        "ifrs18_classifications",
        ["project_id", "requires_human_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ifrs18_classifications_project_id"),
        "ifrs18_classifications",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "classification_evidence",
        sa.Column("classification_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("reference", sa.String(length=300), nullable=False),
        sa.Column("excerpt", sa.String(length=2000), nullable=True),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("produced_by", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_type IN ('BUSINESS_ACTIVITY', 'FINANCIAL_STATEMENT', 'NOTE', 'RULE_SOURCE', 'USER_STATEMENT')",
            name=op.f("ck_classification_evidence_evidence_type_valid"),
        ),
        sa.CheckConstraint(
            "produced_by IN ('AI', 'RULE', 'USER')",
            name=op.f("ck_classification_evidence_produced_by_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["classification_id"],
            ["ifrs18_classifications.id"],
            name=op.f("fk_classification_evidence_classification_id_ifrs18_classifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_evidence")),
    )
    op.create_table(
        "user_reviews",
        sa.Column("classification_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("previous_category", sa.String(length=64), nullable=True),
        sa.Column("new_category", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "action IN ('ACCEPTED', 'DEFERRED', 'OVERRIDDEN')",
            name=op.f("ck_user_reviews_action_valid"),
        ),
        sa.CheckConstraint(
            "new_category IS NULL OR new_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_user_reviews_new_category_valid"),
        ),
        sa.CheckConstraint(
            "previous_category IS NULL OR previous_category IN ('DISCONTINUED_OPERATION', 'FINANCING', 'INCOME_TAX', 'INVESTING', 'OPERATING', 'UNCLASSIFIED')",
            name=op.f("ck_user_reviews_previous_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["classification_id"],
            ["ifrs18_classifications.id"],
            name=op.f("fk_user_reviews_classification_id_ifrs18_classifications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"], ["users.id"], name=op.f("fk_user_reviews_reviewer_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_reviews")),
    )
    op.create_index(
        op.f("ix_user_reviews_classification_id"),
        "user_reviews",
        ["classification_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # audit_logs is append-only (ERD §2, spec §8).
    #
    # Enforced with a trigger rather than role grants: the application often
    # owns its tables in development, and a table owner bypasses REVOKE. A
    # trigger holds regardless of role, and is directly testable.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_logs_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_logs is append-only; % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS audit_logs_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_reviews_classification_id"), table_name="user_reviews")
    op.drop_table("user_reviews")
    op.drop_table("classification_evidence")
    op.drop_index(op.f("ix_ifrs18_classifications_project_id"), table_name="ifrs18_classifications")
    op.drop_index("ix_classification_review_queue", table_name="ifrs18_classifications")
    op.drop_table("ifrs18_classifications")
    op.drop_index(op.f("ix_review_questions_project_id"), table_name="review_questions")
    op.drop_table("review_questions")
    op.drop_index("ix_fsl_statement_summable", table_name="financial_statement_lines")
    op.drop_table("financial_statement_lines")
    op.drop_table("financial_statements")
    op.drop_table("exports")
    op.drop_index(op.f("ix_uploaded_files_sha256"), table_name="uploaded_files")
    op.drop_table("uploaded_files")
    op.drop_index("ix_impact_current", table_name="impact_analyses")
    op.drop_table("impact_analyses")
    op.drop_table("business_activities")
    op.drop_index("ix_audit_project_time", table_name="audit_logs")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_account_synonyms_synonym"), table_name="account_synonyms")
    op.drop_table("account_synonyms")
    op.drop_table("users")
    op.drop_table("normalized_accounts")
    op.drop_table("companies")
    op.drop_index(op.f("ix_classification_rules_rule_id"), table_name="classification_rules")
    op.drop_index(op.f("ix_classification_rules_priority"), table_name="classification_rules")
    op.drop_table("classification_rules")
    # ### end Alembic commands ###
